<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GameDirector.Cli</RootNamespace>
    <AssemblyName>gd</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameDirector.Client\GameDirector.Client.csproj" />
  </ItemGroup>

</Project>
